[workspace]
members = [
  "api",
  "domain",
  "infrastructure",
  "application",
  "shared",
]
resolver = "2"

# Flags for best release performance
[profile.release]
codegen-units = 1
lto = "fat"

# Build for native CPU
[build]
rustflags = ["-C", "target-cpu=native"]