[package]
name = "party-protest"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
  "api",
  "domain",
  "infrastructure",
  "application",
  "shared",
]

# [dependencies]
# rocket = "0.5"
# 
# [dependencies.rocket_dyn_templates]
# version = "~0.2"
# features = ["tera"]