name: Clippy pass

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.rs'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.rs'

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"
# Make sure CI fails on all warnings, including Clippy lints
  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - name: Run sccache-cache
      - uses: mozilla-actions/sccache-action@v0.0.5
      - uses: actions/checkout@v4
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features